[package]
name = "actix-web-test"
version = "0.1.0"
authors = ["ywzjackal <ywzjackal@163.com>"]

[dependencies]
actix = "0.5"
actix-web = {git="https://github.com/actix/actix-web.git"}
futures = "0.1"